name: Run KulaoFilter Daily at 2 AM

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:      

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: 安装依赖 dependencies
        run: pip install requests

      - name: 执行 KulaoFilter.py
        run: python KulaoFilter.py
